dist: bionic
language: generic
before_install:
- |
  echo "Checking if a CI run is needed post commit: ${TRAVIS_COMMIT_RANGE}"
  if ! git diff --name-only ${TRAVIS_COMMIT_RANGE} | grep -qvE '(\.png$)|(\.pdf$)|(\.html$)|^(LICENSE)'
  then
    echo "Only doc files were updated, not running the CI."
    exit
  fi
- sudo add-apt-repository --yes ppa:js-reynaud/kicad-5.1
- sudo apt update -y
- sudo apt install --no-install-recommends -y kicad kicad-symbols kicad-templates
  kicad-footprints inkscape
script:
- cd scripts && ./pcb2svg.sh && cd ..
before_deploy:
- git config --local user.name "PCB Gerber Exporter"
- git config --local user.email "noreply@w4xzr.xyz"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
- ls
- ls Gerbers/
deploy:
  provider: releases
  api_key:
    secure: QyxuMfYTJy0y/UTAB+FolKreqIGQOPxVRhxmJClCQ6ffSTTthR/OIz1p3LqlgW0oAoflEuuoYpdycVUqUiJolreOcuKjLOmHPzhwoQEGjVtQkxWiSVvMqz0LiGo9dG5s5ob9FzDRcLZa5hcqL/1bJiQRTcLs2DVJDKoOkT0FGJSna1vYj4Hr3wZJz+On3BPshVw7BP2WULukmFIDoPKEv0Uiq9vqeknv+KmihZpxBVX6/geO293gtpSrYJb0FTgE2HpznJVXE+FHmhbFlSwFj9eg7rvyOhMxDYZe2UXIopN1oCkTkjF5ymeZQ/cgNnSq74EZ/7rBUUrI466bNGTVNjvMSe/cwvWdE6HLKH7y+dQ5SqZZYr+kuucyUj78JLoDek6riiF00CM0FUpBDeotZgWFHN1KosUFyiJx3nVAHB80Qe5OLYlsmyHssywVGIA0RuShXO89sCFA51vUgdEPOkRe8Ogaqw4+pGXXdNLeSpWNYHWRxNhhDX81RwNjaIGN0uPW9xu/KNKf43nr/wecZZTcLtszHSdF2nxSxBJqPKMnYT147C7GdnmzfOv34Gb6OA84LNk5PwNoUGyLcUq5ZTHAZ/tdOfGLqZJbnxLHwrCyxoa0OSh0VRZxM8s3wzwH5jOVOLXpizvx8OTaDpS5L562Ixred4Ao+kHHYXgx20g=
  file: Gerbers/PRO-113_gerbers.zip
  on:
    repo: w4xzr/PRO-113
  skip_cleanup: 'true'
